function [flog, ulog] = LoadLog( fileIn, dirIn )
%LOADLOG
%   Written: 2021/02/07, J.X.J. Bannwarth
    %% Arguments
    arguments
        fileIn (1,:) char
        dirIn  (1,:) char = 'logs'
    end
    
    %% Load data
    ulog = ulogreader( fullfile( dirIn, fileIn ) );

    %% Extract relevant data to structure
    topics = { ...
        'actuator_outputs'         ; ...
        'distance_sensor'          ; ...
        'input_rc'                 ; ...
        'optical_flow'             ; ...
        'vehicle_attitude'         ; ...
        'vehicle_attitude_setpoint'; ...
        'vehicle_local_position'   ; ...
        'vehicle_rates_setpoint'   ; ...
        'vehicle_vision_position'  ; ...
        };

    nTopics = size(topics, 1);

    dataTmp = readTopicMsgs( ulog, 'TopicNames', topics(:,1), 'InstanceID', ...
          num2cell(zeros( nTopics, 1 )) );

    for ii = 1:size( topics, 1 )
        flog.(topics{ii,1}) = dataTmp(ii,:).TopicMessages{1};
    end
end